name: 'antigravity_project'
version: '1.0.0'
config-version: 2

profile: 'antigravity'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  antigravity_project:
    +persist_docs:
      relation: true
      columns: true
    bronze:
      +tags: ["deploy"]
    silver:
      +tags: ["deploy"]
    gold:
      +tags: ["deploy"]

tests:
  antigravity_project:
    +tags: ["prod_test"]
