antigravity:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('GCP_SCHEMA', 'dev') }}"
      threads: 4
      timeout_seconds: 300
      location: europe-west2
      priority: interactive
    ci:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('GCP_SCHEMA', 'ci') }}"
      threads: 4
      timeout_seconds: 300
      location: europe-west2
      priority: interactive
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      # dataset: "{{ env_var('GCP_SCHEMA', 'main') }}"
      dataset: "main"
      threads: 4
      timeout_seconds: 300
      location: europe-west2
      priority: interactive
