antigravity:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: modelling-demo
      dataset: "{{ env_var('GCP_DATASET', 'antigravity_dev') }}"
      threads: 4
      location: europe-west2
    prod:
      type: bigquery
      method: oauth
      project: modelling-demo
      dataset: "{{ env_var('GCP_DATASET', 'antigravity_prod') }}"
      threads: 4
      location: europe-west2
