version: 2

models:
  - name: dim_researchers
    description: "Curated dimension table for antigravity researchers."
    columns:
      - name: researcher_id
        tests:
          - unique
          - not_null:
              config:
                tags: ['prod_test']

  - name: fct_levitation_events
    description: "Fact table for levitation events, enriched with researcher, vessel, and location details."
    columns:
      - name: event_id
        tests:
          - unique
          - not_null:
              config:
                tags: ['prod_test']
      - name: gravity_g
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: -1
                max_value: 2
              config:
                tags: ['prod_test']
      - name: researcher_id
        tests:
          - not_null:
              config:
                tags: ['prod_test']

  - name: dim_vessels
    description: "Dimension table for antigravity vessels."
    columns:
      - name: vessel_id
        tests:
          - unique
          - not_null

  - name: dim_locations
    description: "Dimension table for research locations."
    columns:
      - name: location_id
        tests:
          - unique
          - not_null
