name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dagger SDK
        run: pip install dagger-io anyio

      - name: Setup Dagger CLI
        uses: dagger/dagger-for-github@v7
        with:
          install-only: true

      - name: Run Dagger Pipeline
        run: dagger run python ci/dagger_pipeline.py
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
